/**
 * `mercury host bot service install|uninstall --alias <a>` — per-alias service units (§10, B1-3).
 *
 * Same machinery as `host service` (docs/host-installer.md M4), one unit PER BOT:
 *
 *   - macOS: launchd agent at `~/Library/LaunchAgents/com.mercury.bot.<alias>.plist`, whose
 *     wrapper sources `mercury.env` (the bot reads host defaults like MERCURY_PORT from it) and
 *     execs `mercury host bot run --alias <alias>`. The bot's TOKEN never comes from the env
 *     file — it comes from bot-credentials.json (§4.2) — so the wrapper is the host wrapper
 *     pattern without embedding any bot secret.
 *   - Linux: systemd user unit `mercury-bot-<alias>.service` with an absolute EnvironmentFile.
 *
 * The alias is filesystem- and systemd-safe by validation (§4.1), so it may appear in unit
 * names, labels and wrapper paths verbatim.
 *
 * Uninstall (§17 item 7) removes the unit AND the bot's local state: the config file, the
 * state file, the alias's entry in the SHARED bot-credentials.json, and the alias's
 * `tok-bot-<alias>-…:bot-<alias>` entry in MERCURY_API_TOKENS (preserving every other entry
 * and hand-set var, #677's preservation rule). It ALWAYS prints the §17.7 consequence: the
 * bot's Runs remain in the database but become readable only to an admin or observer token,
 * because the owner's token is gone. Anything that writes requires --yes (§11 guardrails);
 * without it the command prints the plan and writes nothing.
 */

import { basename, join } from 'node:path';
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { homedir } from 'node:os';
import { envFilePath, resolveMercuryBin } from '../service.ts';
import { BOT_ALIAS_RE } from './config.ts';

/** The §4.1 alias contract is also a path-safety contract: unit names and file paths are built from it. */
function assertAlias(alias: string): void {
  if (!BOT_ALIAS_RE.test(alias)) {
    throw new Error(`bot alias must match ${BOT_ALIAS_RE.source}, got '${alias}'`);
  }
}

/** The launchd label for one bot (macOS). */
export function botLaunchdLabel(alias: string): string {
  return `com.mercury.bot.${alias}`;
}

/** The systemd user unit name for one bot (Linux). */
export function botServiceName(alias: string): string {
  return `mercury-bot-${alias}.service`;
}

/** The launchd plist path for one bot (macOS). */
export function botPlistPath(alias: string, env: NodeJS.ProcessEnv = process.env): string {
  return join(homedir(), 'Library', 'LaunchAgents', `${botLaunchdLabel(alias)}.plist`);
}

/** The systemd user unit path for one bot (Linux). */
export function botUnitPath(alias: string, env: NodeJS.ProcessEnv = process.env): string {
  const base = env.XDG_CONFIG_HOME?.trim() || join(homedir(), '.config');
  return join(base, 'systemd', 'user', botServiceName(alias));
}

/** The per-bot launchd wrapper path (macOS): sources mercury.env, execs the bot run loop. */
export function botWrapperPath(alias: string, env: NodeJS.ProcessEnv = process.env): string {
  const base = env.XDG_STATE_HOME?.trim() || join(homedir(), '.local', 'state');
  return join(base, 'mercury', 'bots', `run-${alias}.sh`);
}

/** The launchd wrapper script text for one bot. Deterministic for the same inputs. */
export function botWrapper(mercuryBin: string, envFile: string, alias: string): string {
  return `#!/bin/bash
# Generated by \`mercury host bot service install --alias ${alias}\` (dispatcher-bot-design §10).
# launchd has no EnvironmentFile, so this wrapper sources mercury.env the same way the host
# service does, then execs the bot's run loop. The bot's token comes from bot-credentials.json
# (§4.2), never from this file.
set -a
source "${envFile}"
set +a
exec "${mercuryBin}" host bot run --alias "${alias}"
`;
}

/** The systemd user unit text for one bot. Deterministic for the same inputs. */
export function botUnit(mercuryBin: string, envFile: string, alias: string): string {
  return `[Unit]
Description=Mercury bot ${alias} (dispatcher bot, one process per alias)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=%h
EnvironmentFile=${envFile}
ExecStart=${mercuryBin} host bot run --alias ${alias}
Restart=on-failure
RestartSec=5
TimeoutStopSec=15

[Install]
WantedBy=default.target
`;
}

/** The launchd plist text for one bot. Deterministic for the same inputs. */
export function botPlist(wrapper: string, stateDir: string, alias: string): string {
  const log = join(stateDir, 'mercury', 'bots', `${alias}.log`);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${botLaunchdLabel(alias)}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${wrapper}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${log}</string>
  <key>StandardErrorPath</key>
  <string>${log}</string>
</dict>
</plist>
`;
}

/** The §17.7 teardown consequence, printed on EVERY uninstall (with or without --yes). */
export function teardownConsequence(alias: string): string {
  return `Teardown consequence (§17.7): Runs owned by bot-${alias} remain in the database, but ` +
    `become readable only to an admin or observer token once the owner's token is gone.`;
}

export interface BotServiceInstallOptions {
  dryRun: boolean;
}

export function parseBotServiceInstallArgs(args: string[]): { alias: string } & BotServiceInstallOptions {
  const out = { alias: '', dryRun: false };
  for (let i = 0; i < args.length; i++) {
    const a = args[i]!;
    if (a === '--alias') {
      out.alias = args[++i] ?? '';
    } else if (a.startsWith('--alias=')) {
      out.alias = a.slice('--alias='.length);
    } else if (a === '--dry-run') {
      out.dryRun = true;
    } else {
      throw new Error(`host bot service install: unknown argument '${a}'. Expected --alias <a> and --dry-run`);
    }
  }
  if (!out.alias) throw new Error('host bot service install: --alias <a> is required');
  return out;
}

/** Install one bot's service: write the unit (and wrapper on macOS), enable it. */
export function installBotService(
  platform: NodeJS.Platform,
  alias: string,
  io: { out: (s: string) => void; err: (s: string) => void },
  env: NodeJS.ProcessEnv = process.env,
  dryRun = false,
): number {
  assertAlias(alias);
  let bin: string;
  try {
    bin = resolveMercuryBin(env);
  } catch (e) {
    io.err(`host bot service: ${(e as Error).message}\n`);
    return 1;
  }
  const envFile = envFilePath(env);
  if (platform === 'darwin') {
    const wrapper = botWrapperPath(alias, env);
    const plist = botPlistPath(alias, env);
    const stateDir = env.XDG_STATE_HOME?.trim() || join(homedir(), '.local', 'state');
    if (dryRun) {
      io.out(`mercury host bot service install --alias ${alias} --dry-run (macOS)\n`);
      io.out(`  wrapper: ${wrapper}\n`);
      io.out(`  plist:   ${plist}\n`);
      io.out(botPlist(wrapper, stateDir, alias) + '\n');
      return 0;
    }
    if (!existsSync(envFile)) {
      io.err(`host bot service: ${envFile} does not exist. Run \`mercury host setup\` first (M3).\n`);
      return 1;
    }
    mkdirSync(join(stateDir, 'mercury', 'bots'), { recursive: true });
    writeFileSync(wrapper, botWrapper(bin, envFile, alias), { mode: 0o700 });
    chmodSync(wrapper, 0o700);
    mkdirSync(join(homedir(), 'Library', 'LaunchAgents'), { recursive: true });
    writeFileSync(plist, botPlist(wrapper, stateDir, alias), { mode: 0o644 });
    try {
      // Same idempotent load choreography as the host service (issue #650): print decides,
      // bootout only when loaded, then bootstrap fresh.
      const uid = typeof process.getuid === 'function' ? process.getuid() : null;
      if (uid === null) throw new Error('cannot determine uid for launchctl gui domain');
      const target = `gui/${uid}/${botLaunchdLabel(alias)}`;
      let loaded = true;
      try {
        execFileSync('launchctl', ['print', target], { timeout: 10000, stdio: 'ignore' });
      } catch {
        loaded = false;
      }
      if (loaded) {
        try {
          execFileSync('launchctl', ['bootout', target], { timeout: 10000, stdio: 'ignore' });
        } catch {
          // bootout raced with an unload; bootstrap below decides success
        }
      }
      execFileSync('launchctl', ['bootstrap', `gui/${uid}`, plist], { timeout: 10000 });
      io.out(`Installed and loaded ${botLaunchdLabel(alias)} (${plist}).\n`);
    } catch (e) {
      io.err(`host bot service: launchctl bootstrap failed: ${(e as Error).message}\n`);
      return 1;
    }
    return 0;
  }
  // Linux (systemd user unit)
  const unitPath = botUnitPath(alias, env);
  if (dryRun) {
    io.out(`mercury host bot service install --alias ${alias} --dry-run (systemd user)\n`);
    io.out(`  unit: ${unitPath}\n`);
    io.out(botUnit(bin, envFile, alias) + '\n');
    return 0;
  }
  if (!existsSync(envFile)) {
    io.err(`host bot service: ${envFile} does not exist. Run \`mercury host setup\` first (M3).\n`);
    return 1;
  }
  mkdirSync(join(unitPath, '..'), { recursive: true });
  writeFileSync(unitPath, botUnit(bin, envFile, alias), { mode: 0o644 });
  try {
    execFileSync('systemctl', ['--user', 'daemon-reload'], { timeout: 10000 });
    execFileSync('systemctl', ['--user', 'enable', '--now', botServiceName(alias)], { timeout: 10000 });
    io.out(`Installed and enabled ${botServiceName(alias)} (${unitPath}).\n`);
    io.out('Hint: run `loginctl enable-linger $USER` so the unit survives logout.\n');
  } catch (e) {
    io.err(`host bot service: systemctl failed: ${(e as Error).message}\n`);
    return 1;
  }
  return 0;
}

export interface BotServiceUninstallOptions {
  yes: boolean;
  keepEnv: boolean;
  reassignOwner: string | null;
}

export function parseBotServiceUninstallArgs(args: string[]): { alias: string } & BotServiceUninstallOptions {
  const out: { alias: string } & BotServiceUninstallOptions = { alias: '', yes: false, keepEnv: false, reassignOwner: null };
  for (let i = 0; i < args.length; i++) {
    const a = args[i]!;
    if (a === '--alias') {
      out.alias = args[++i] ?? '';
    } else if (a.startsWith('--alias=')) {
      out.alias = a.slice('--alias='.length);
    } else if (a === '--yes') {
      out.yes = true;
    } else if (a === '--keep-env') {
      out.keepEnv = true;
    } else if (a === '--reassign-runs') {
      const v = args[++i];
      if (v === undefined || v.trim() === '') {
        throw new Error('host bot service uninstall: --reassign-runs requires an owner value');
      }
      out.reassignOwner = v;
    } else if (a.startsWith('--reassign-runs=')) {
      const v = a.slice('--reassign-runs='.length);
      if (v.trim() === '') {
        throw new Error('host bot service uninstall: --reassign-runs requires an owner value');
      }
      out.reassignOwner = v;
    } else {
      throw new Error(`host bot service uninstall: unknown argument '${a}'. Expected --alias <a>, --yes, --keep-env, --reassign-runs <owner>`);
    }
  }
  if (!out.alias) throw new Error('host bot service uninstall: --alias <a> is required');
  return out;
}

/**
 * Remove the alias's `token:bot-<alias>` entry from the MERCURY_API_TOKENS value in the env
 * file, preserving every other entry and every other line (#677's preservation rule). Returns
 * the number of entries removed (0 when the alias is absent; duplicates each count). Throws on
 * a malformed line rather than guessing.
 */
export function removeBotTokenFromEnv(envText: string, alias: string): { text: string; removed: number } {
  const lines = envText.split('\n');
  let removed = 0;
  const outLines = lines.map((line, lineNo) => {
    const m = /^MERCURY_API_TOKENS=(.*)$/.exec(line);
    if (!m) return line;
    const entries = m[1]!.split(',').map((e) => e.trim()).filter((e) => e !== '');
    // The same strict shape src/config.ts's parseTokens enforces at load: exactly one colon and
    // both halves non-empty. An unparseable line must fail the edit rather than survive a
    // "successful" uninstall half-edited; the error carries the entry INDEX, never token material.
    for (let ei = 0; ei < entries.length; ei++) {
      const parts = entries[ei]!.split(':');
      // parseTokens parity (src/config.ts): exactly two segments, both non-empty AFTER trimming —
      // 'tok: ' is malformed, and 'tok-bot: bot-nightly' (spaces around the colon) is valid.
      if (parts.length !== 2 || !parts[0]!.trim() || !parts[1]!.trim()) {
        throw new Error(`MERCURY_API_TOKENS entry ${ei} in line ${lineNo + 1} is not 'token:owner'; fix mercury.env by hand`);
      }
    }
    const kept = entries.filter((e) => {
      const [tok, owner] = e.split(':');
      if (owner!.trim() === `bot-${alias}`) { removed++; return false; }
      return true;
    });
    if (kept.length === 0) return '';
    return `MERCURY_API_TOKENS=${kept.join(', ')}`;
  });
  return { text: outLines.join('\n'), removed };
}

/**
 * Remove the alias's entry from the SHARED bot-credentials.json, preserving the other bots'
 * entries and the file's 0600 mode. Returns true when an entry was removed.
 */
export function removeBotCredential(alias: string, env: NodeJS.ProcessEnv = process.env): boolean {
  const path = botCredentialsPathFor(env);
  if (!existsSync(path)) return false;
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(path, 'utf8'));
  } catch (e) {
    // Uninstall must not claim success while leaving a token copy on disk: a malformed
    // credentials file fails the uninstall loudly (the alias entry may still be inside).
    throw new Error(`cannot update ${path}: not valid JSON (${(e as Error).message}); remove the '${alias}' entry by hand`);
  }
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error(`cannot update ${path}: must be a JSON object keyed by bot alias; remove the '${alias}' entry by hand`);
  }
  const obj = raw as Record<string, unknown>;
  // Own-property check: `alias in obj` also matches Object.prototype ('constructor'), which
  // would report success while removing nothing.
  if (!Object.prototype.hasOwnProperty.call(obj, alias)) return false;
  delete obj[alias];
  writeFileSync(path, JSON.stringify(obj, null, 2) + '\n', { mode: 0o600 });
  // writeFileSync's mode applies only at CREATION; an existing file keeps its bits, so enforce
  // the 0600 gate this module promises (a drifted mode must not survive a rewrite).
  chmodSync(path, 0o600);
  return true;
}

function botCredentialsPathFor(env: NodeJS.ProcessEnv): string {
  const xdg = env.XDG_CONFIG_HOME;
  const base = xdg && xdg.trim() !== '' ? xdg : join(homedir(), '.config');
  return join(base, 'mercury', 'bot-credentials.json');
}

/** The bot's local state file (§10): removed on uninstall, never on install. */
export function botStateFile(alias: string, env: NodeJS.ProcessEnv = process.env): string {
  const base = env.XDG_STATE_HOME?.trim() || join(homedir(), '.local', 'state');
  return join(base, 'mercury', 'bots', `${alias}.state.json`);
}

/** The bot's config file (§4.1): removed on uninstall with --yes. */
export function botConfigFile(alias: string, env: NodeJS.ProcessEnv = process.env): string {
  const base = env.XDG_CONFIG_HOME?.trim() || join(homedir(), '.config');
  return join(base, 'mercury', 'bots', `${alias}.json`);
}

/**
 * Uninstall one bot's service AND its local state (§17 item 7). Prints the §17.7 consequence
 * on every path. Without --yes it prints the plan and writes nothing (exit 1).
 */
export function uninstallBotService(
  platform: NodeJS.Platform,
  alias: string,
  io: { out: (s: string) => void; err: (s: string) => void },
  env: NodeJS.ProcessEnv = process.env,
  opts: BotServiceUninstallOptions = { yes: false, keepEnv: false, reassignOwner: null },
): number {
  assertAlias(alias);
  const plist = botPlistPath(alias, env);
  const unitPath = botUnitPath(alias, env);
  const wrapper = botWrapperPath(alias, env);
  const stateFile = botStateFile(alias, env);
  const configFile = botConfigFile(alias, env);
  const envFile = envFilePath(env);
  io.out(`Plan: remove ${platform === 'darwin' ? `${plist} (and its wrapper)` : unitPath}, ${stateFile}, ${configFile},` +
    ` the '${alias}' entry in the shared bot credentials file,` +
    `${opts.keepEnv ? '' : ` the bot-${alias} entry in MERCURY_API_TOKENS,`} then print the §17.7 consequence.\n`);
  io.out(teardownConsequence(alias) + '\n');
  if (opts.reassignOwner !== null) {
    // Checked after the consequence print: the contract is that uninstall ALWAYS states what
    // happens to the bot's Runs, including on this refusal path.
    io.err(`host bot service uninstall: --reassign-runs is not supported yet: no owner-transfer API exists ` +
      `(aywengo/mercury#760). The bot's Runs stay owned by bot-${alias}.\n`);
    return 1;
  }
  if (!opts.yes) {
    io.err('host bot service uninstall: nothing written — re-run with --yes to remove the bot.\n');
    return 1;
  }
  if (platform === 'darwin') {
    if (existsSync(plist)) {
      try {
        execFileSync('launchctl', ['bootout', `gui/${typeof process.getuid === 'function' ? process.getuid() : ''}/${botLaunchdLabel(alias)}`], { timeout: 10000, stdio: 'ignore' });
      } catch {
        // not loaded is fine
      }
      try {
        unlinkSync(plist);
      } catch {
        // ignore
      }
      io.out(`Removed ${botLaunchdLabel(alias)}.\n`);
    } else {
      io.out(`${botLaunchdLabel(alias)} is not installed.\n`);
    }
  } else {
    if (existsSync(unitPath)) {
      try {
        execFileSync('systemctl', ['--user', 'disable', '--now', botServiceName(alias)], { timeout: 10000 });
      } catch {
        // not enabled is fine
      }
      try {
        unlinkSync(unitPath);
      } catch {
        // ignore
      }
      try {
        execFileSync('systemctl', ['--user', 'daemon-reload'], { timeout: 10000, stdio: 'ignore' });
      } catch {
        // ignore
      }
      io.out(`Removed ${botServiceName(alias)}.\n`);
    } else {
      io.out(`${botServiceName(alias)} is not installed.\n`);
    }
  }
  if (existsSync(wrapper)) {
    try {
      unlinkSync(wrapper);
    } catch {
      // ignore
    }
  }
  for (const f of [stateFile, configFile]) {
    if (existsSync(f)) {
      try {
        unlinkSync(f);
        io.out(`Removed ${basename(f)}.\n`);
      } catch {
        // ignore
      }
    }
  }
  try {
    if (removeBotCredential(alias, env)) {
      io.out(`Removed the '${alias}' entry from the shared bot credentials file.\n`);
    }
  } catch (e) {
    io.err(`host bot service: ${(e as Error).message}\n`);
    return 1;
  }
  if (!opts.keepEnv && existsSync(envFile)) {
    try {
      const { text, removed } = removeBotTokenFromEnv(readFileSync(envFile, 'utf8'), alias);
      if (removed > 0) {
        writeFileSync(envFile, text, { mode: 0o600 });
        // Same mode-repair rule as removeBotCredential: writeFileSync's mode applies only at
        // creation, so a mercury.env that drifted to 0644 must be repaired, not left readable.
        chmodSync(envFile, 0o600);
        io.out(`Removed the bot-${alias} entry from MERCURY_API_TOKENS in ${envFile}.\n`);
      } else {
        io.out(`No bot-${alias} entry found in MERCURY_API_TOKENS (${envFile}); nothing to remove there.\n`);
      }
    } catch (e) {
      io.err(`host bot service: could not update ${envFile}: ${(e as Error).message}\n`);
      io.err(`Remove the bot-${alias} entry from MERCURY_API_TOKENS by hand — the token still authorizes until then.\n`);
      return 1;
    }
  }
  return 0;
}
